name: Build Website
on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
  
      - name: Copy Raw Files
        shell: bash
        run: |
          set -euo pipefail
          cd ${{ github.workspace }}
          ls -al
          mkdir ./public
          cp -r ./rcd ./public/rcd
          cp -r ./tree ./public/tree
          ls -al
            
      - name: Build Zola recipe site
        shell: bash
        run: |
          set -euo pipefail
          image="ghcr.io/getzola/zola:v0.22.0"
          echo "Using image: $image"
  
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -w "/workspace/recipes" \
            "$image" build --output-dir "/workspace/public/recipes"
  
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: "./public"
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
